/**
 * Build — no dependencies, plain Node.
 *
 *   dist/index.html   the assembled single-file UI
 *   dist/worker.js    Cloudflare Worker, Service Worker format — paste into the dashboard editor
 *   dist/worker.mjs   Cloudflare Worker, ES module format      — `wrangler deploy`
 *
 * The Worker bundles are produced by concatenating the proxy core and the
 * Cloudflare host with their import/export syntax removed, so the pasted file
 * needs no build step on Cloudflare's side. The build checks its own output
 * (HTML round-trip, syntax, no leftover module syntax) before writing.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import vm from 'node:vm';
import { assembleHtml } from '../src/ui/assemble.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));

/** Remove ES module syntax so sources can be concatenated into one classic script. */
export function stripModuleSyntax(src) {
  return src
    .replace(/^#!.*\n/, '')
    .replace(/^import\s[^;]+;[ \t]*\n?/gm, '')
    .replace(/^export\s+(async\s+function|function|const|let|var|class)\b/gm, '$1')
    .replace(/^export\s*\{[^}]*\};?[ \t]*\n?/gm, '');
}

/** Embed arbitrary text as a JS template literal. */
export function toTemplateLiteral(text) {
  return '`' + text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

function banner(format) {
  const deploy = format === 'sw'
    ? [
        ' * DEPLOY (dashboard, no CLI):',
        ' *   1. dash.cloudflare.com → Workers & Pages → Create → Workers → "Start with Hello World!"',
        ' *   2. Deploy, then "Edit code" → select ALL existing code → delete → paste this file → Deploy',
        ' *   3. Open https://<name>.<your-subdomain>.workers.dev',
      ]
    : [
        ' * DEPLOY: `npx wrangler deploy` (uses wrangler.toml → main = "dist/worker.mjs")',
      ];
  return [
    '/**',
    ` * MCP Tester ${pkg.version} — Cloudflare Worker (${format === 'sw' ? 'Service Worker' : 'ES module'} format)`,
    ' * GENERATED by scripts/build.mjs — do not edit; change src/ and rebuild.',
    ' *',
    ...deploy,
    ' *',
    ' * OPTIONAL: set ALLOWED_ORIGINS (Settings → Variables) to restrict which MCP hosts',
    ' * this Worker will proxy to, e.g. "developer.hsbc.com". This Worker is public —',
    ' * put Cloudflare Access in front of it before using it with credentials.',
    ' */',
    '',
  ].join('\n');
}

export function build({ write = true } = {}) {
  const html = assembleHtml();
  const core = stripModuleSyntax(readFileSync(join(ROOT, 'src/core/proxy.js'), 'utf8'));
  const host = stripModuleSyntax(readFileSync(join(ROOT, 'src/hosts/cloudflare.js'), 'utf8'));
  const htmlConst = 'const HTML = ' + toTemplateLiteral(html) + ';\n\n';

  const sw = banner('sw') + htmlConst + core + '\n' + host + '\n' +
    'addEventListener("fetch", function (event) {\n' +
    '  event.respondWith(handleRequest(event.request, typeof ALLOWED_ORIGINS !== "undefined" ? ALLOWED_ORIGINS : ""));\n' +
    '});\n';

  const mod = banner('module') + htmlConst + core + '\n' + host + '\n' +
    'export default {\n' +
    '  fetch(request, env) {\n' +
    '    return handleRequest(request, (env && env.ALLOWED_ORIGINS) || "");\n' +
    '  },\n' +
    '};\n';

  // ── self-checks ──
  const roundTrip = vm.runInNewContext(toTemplateLiteral(html));
  if (roundTrip !== html) throw new Error('HTML template literal does not round-trip');
  new vm.Script(sw, { filename: 'worker.js' });                    // throws on syntax error
  if (/^\s*(import|export)\s/m.test(sw)) throw new Error('module syntax left in worker.js');
  if ((mod.match(/^export\s/gm) || []).length !== 1) throw new Error('worker.mjs must have exactly one export');

  if (write) {
    mkdirSync(DIST, { recursive: true });
    writeFileSync(join(DIST, 'index.html'), html);
    writeFileSync(join(DIST, 'worker.js'), sw);
    writeFileSync(join(DIST, 'worker.mjs'), mod);
  }
  return { html, sw, mod };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const { html, sw, mod } = build();
  const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + ' KB';
  console.log(`MCP Tester ${pkg.version} built:`);
  console.log(`  dist/index.html  ${kb(html)}`);
  console.log(`  dist/worker.js   ${kb(sw)}   ← paste into the Cloudflare dashboard`);
  console.log(`  dist/worker.mjs  ${kb(mod)}   ← wrangler deploy`);
}
